name: PortfolioPanda
favicon: null
layout_spectrum: 0.852944073267281
typography_spectrum: 0.5887683071196079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5842419830150902
  lightness: 0.8021101544145495
  saturation: 0.18175695417448878
  rhythmicContrast: 0.12695953366346657
purpose: []
